
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: 'root'
  password: 'root'

development:
  <<: *default
  database: phones_api

test:
  <<: *default
  database: phones_api

production:
  <<: *default
  database: phones_api

